[{"ContainerToolsException.Message":"Visual Studio Container Tools requires Docker to be running before building, debugging or running a containerized project.  For more info, please see: https://aka.ms/DockerToolsTroubleshooting","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))\nIf the error persists, try restarting Docker Desktop.\n ---> Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))\n   at Microsoft.Docker.DockerWorkspace.PrepareForLaunchAsync(DockerDevelopmentMode dockerDevelopmentMode, Boolean noBuild, IDockerLogger logger, String dockerComposeUpArguments, CancellationToken cancellationToken)\nError code: DT1001\nSeverity: Error\nCommand line: docker-compose  -f \"/Users/adrianbooth67/Projects/Viridia/Device Monitoring Platform/Monitoring/docker-compose.yml\" -f \"/Users/adrianbooth67/Projects/Viridia/Device Monitoring Platform/Monitoring/docker-compose.override.yml\" -f \"/Users/adrianbooth67/Projects/Viridia/Device Monitoring Platform/Monitoring/obj/Docker/docker-compose.vs.debug.g.yml\" -p dockercompose1118994426062358019 --no-ansi up -d --build --remove-orphans\nCommand exit code: 255\nCommand output: \nCommand error: [49521] Failed to execute script docker-compose\nTraceback (most recent call last):\n  File \"site-packages/urllib3/connectionpool.py\", line 677, in urlopen\n  File \"site-packages/urllib3/connectionpool.py\", line 392, in _make_request\n  File \"http/client.py\", line 1252, in request\n  File \"http/client.py\", line 1298, in _send_request\n  File \"http/client.py\", line 1247, in endheaders\n  File \"http/client.py\", line 1026, in _send_output\n  File \"http/client.py\", line 966, in send\n  File \"site-packages/docker/transport/unixconn.py\", line 43, in connect\nFileNotFoundError: [Errno 2] No such file or directory\nDuring handling of the above exception, another exception occurred:\nTraceback (most recent call last):\n  File \"site-packages/requests/adapters.py\", line 449, in send\n  File \"site-packages/urllib3/connectionpool.py\", line 727, in urlopen\n  File \"site-packages/urllib3/util/retry.py\", line 403, in increment\n  File \"site-packages/urllib3/packages/six.py\", line 734, in reraise\n  File \"site-packages/urllib3/connectionpool.py\", line 677, in urlopen\n  File \"site-packages/urllib3/connectionpool.py\", line 392, in _make_request\n  File \"http/client.py\", line 1252, in request\n  File \"http/client.py\", line 1298, in _send_request\n  File \"http/client.py\", line 1247, in endheaders\n  File \"http/client.py\", line 1026, in _send_output\n  File \"http/client.py\", line 966, in send\n  File \"site-packages/docker/transport/unixconn.py\", line 43, in connect\nurllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))\nDuring handling of the above exception, another exception occurred:\nTraceback (most recent call last):\n  File \"site-packages/docker/api/client.py\", line 205, in _retrieve_server_version\n  File \"site-packages/docker/api/daemon.py\", line 181, in version\n  File \"site-packages/docker/utils/decorators.py\", line 46, in inner\n  File \"site-packages/docker/api/client.py\", line 228, in _get\n  File \"site-packages/requests/sessions.py\", line 543, in get\n  File \"site-packages/requests/sessions.py\", line 530, in request\n  File \"site-packages/requests/sessions.py\", line 643, in send\n  File \"site-packages/requests/adapters.py\", line 498, in send\nrequests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))\nDuring handling of the above exception, another exception occurred:\nTraceback (most recent call last):\n  File \"docker-compose\", line 3, in <module>\n  File \"compose/cli/main.py\", line 67, in main\n  File \"compose/cli/main.py\", line 123, in perform_command\n  File \"compose/cli/command.py\", line 69, in project_from_options\n  File \"compose/cli/command.py\", line 132, in get_project\n  File \"compose/cli/docker_client.py\", line 43, in get_client\n  File \"compose/cli/docker_client.py\", line 170, in docker_client\n  File \"site-packages/docker/api/client.py\", line 188, in __init__\n  File \"site-packages/docker/api/client.py\", line 213, in _retrieve_server_version\ndocker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))\n\n   --- End of inner exception stack trace ---\n   at Microsoft.Docker.DockerWorkspace.PrepareForLaunchAsync(DockerDevelopmentMode dockerDevelopmentMode, Boolean noBuild, IDockerLogger logger, String dockerComposeUpArguments, CancellationToken cancellationToken)\n   at Microsoft.Docker.BuildTasks.PrepareForLaunch.ExecuteCoreAsync(DockerBuildTaskContext context)\n   at Microsoft.Docker.BuildTasks.DockerBuildTask.ExecuteAsync(DockerBuildTaskContext context)\nError code: DT1001\nSeverity: Error\n"},{"ContainerToolsException.Message":"Error response from daemon: Conflict. The container name \"/Monitoring\" is already in use by container \"7b05bb67d4ebe48f7ef4b15a197fe3588da769bff819eb3418f0ea09b9683798\". You have to remove (or rename) that container to be able to reuse that name. If the error persists, try restarting Docker Desktop.","ContainerToolsException.ErrorCode":"DT1001","ContainerToolsException.StackTrace":"   at Microsoft.Docker.DockerWorkspace.PrepareForLaunchAsync(DockerDevelopmentMode dockerDevelopmentMode, Boolean noBuild, IDockerLogger logger, String dockerComposeUpArguments, CancellationToken cancellationToken)\n   at Microsoft.Docker.BuildTasks.PrepareForLaunch.ExecuteCoreAsync(DockerBuildTaskContext context)\n   at Microsoft.Docker.BuildTasks.DockerBuildTask.ExecuteAsync(DockerBuildTaskContext context)","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: Error response from daemon: Conflict. The container name \"/Monitoring\" is already in use by container \"7b05bb67d4ebe48f7ef4b15a197fe3588da769bff819eb3418f0ea09b9683798\". You have to remove (or rename) that container to be able to reuse that name.\n   at Microsoft.Docker.DockerWorkspace.PrepareForLaunchAsync(DockerDevelopmentMode dockerDevelopmentMode, Boolean noBuild, IDockerLogger logger, String dockerComposeUpArguments, CancellationToken cancellationToken)\nError code: DT1001\nSeverity: Error\nCommand line: docker-compose  -f \"/Users/adrianbooth67/Projects/Viridia/Dummy/MonitoringPlatform/docker-compose.yml\" -f \"/Users/adrianbooth67/Projects/Viridia/Dummy/MonitoringPlatform/docker-compose.override.yml\" -f \"/Users/adrianbooth67/Projects/Viridia/Dummy/MonitoringPlatform/obj/Docker/docker-compose.vs.debug.g.yml\" -p dockercompose5800756500010996833 --ansi never up -d --build --remove-orphans\nCommand exit code: 1\nCommand output: #1 [internal] load build definition from Dockerfile\n#1 transferring dockerfile: 32B done\n#1 DONE 0.0s\n#2 [internal] load .dockerignore\n#2 transferring context: 35B done\n#2 DONE 0.0s\n#3 [internal] load metadata for mcr.microsoft.com/dotnet/aspnet:7.0\n#3 DONE 0.0s\n#4 [base 1/2] FROM mcr.microsoft.com/dotnet/aspnet:7.0@sha256:db181c925678b0c193c6bdeaf9d04759051aa0a4ab12f91c267f32acc765f35f\n#4 DONE 0.0s\n#5 [base 2/2] WORKDIR /app\n#5 CACHED\n#6 exporting to image\n#6 exporting layers done\n#6 writing image sha256:5bfada8a93c3ded66b5ba666e86479ab15f1b7a980bfb506f3d0cc6de07730c9 done\n#6 naming to docker.io/library/monitoring:dev done\n#6 DONE 0.0s\nCommand error: Network dockercompose5800756500010996833_default  Creating\nNetwork dockercompose5800756500010996833_default  Created\nContainer Monitoring  Creating\nError response from daemon: Conflict. The container name \"/Monitoring\" is already in use by container \"7b05bb67d4ebe48f7ef4b15a197fe3588da769bff819eb3418f0ea09b9683798\". You have to remove (or rename) that container to be able to reuse that name.\n"},{"ContainerToolsException.Message":"Error response from daemon: Conflict. The container name \"/Monitoring\" is already in use by container \"1d10f0bbd58ebfe7581d5c9db8655024e88ca485f7081e41685b44f825a3eace\". You have to remove (or rename) that container to be able to reuse that name. If the error persists, try restarting Docker Desktop.","ContainerToolsException.ErrorCode":"DT1001","ContainerToolsException.StackTrace":"   at Microsoft.Docker.DockerWorkspace.PrepareForLaunchAsync(DockerDevelopmentMode dockerDevelopmentMode, Boolean noBuild, IDockerLogger logger, String dockerComposeUpArguments, CancellationToken cancellationToken)\n   at Microsoft.Docker.BuildTasks.PrepareForLaunch.ExecuteCoreAsync(DockerBuildTaskContext context)\n   at Microsoft.Docker.BuildTasks.DockerBuildTask.ExecuteAsync(DockerBuildTaskContext context)","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: Error response from daemon: Conflict. The container name \"/Monitoring\" is already in use by container \"1d10f0bbd58ebfe7581d5c9db8655024e88ca485f7081e41685b44f825a3eace\". You have to remove (or rename) that container to be able to reuse that name.\n   at Microsoft.Docker.DockerWorkspace.PrepareForLaunchAsync(DockerDevelopmentMode dockerDevelopmentMode, Boolean noBuild, IDockerLogger logger, String dockerComposeUpArguments, CancellationToken cancellationToken)\nError code: DT1001\nSeverity: Error\nCommand line: docker-compose  -f \"/Users/adrianbooth67/Projects/Viridia/Dummy/MonitoringPlatform/docker-compose.yml\" -f \"/Users/adrianbooth67/Projects/Viridia/Dummy/MonitoringPlatform/docker-compose.override.yml\" -f \"/Users/adrianbooth67/Projects/Viridia/Dummy/MonitoringPlatform/obj/Docker/docker-compose.vs.debug.g.yml\" -p dockercompose5800756500010996833 --ansi never up -d\nCommand exit code: 1\nCommand output: \nCommand error: Network dockercompose5800756500010996833_default  Creating\nNetwork dockercompose5800756500010996833_default  Created\nContainer Monitoring  Creating\nError response from daemon: Conflict. The container name \"/Monitoring\" is already in use by container \"1d10f0bbd58ebfe7581d5c9db8655024e88ca485f7081e41685b44f825a3eace\". You have to remove (or rename) that container to be able to reuse that name.\n"},{"ContainerToolsException.Message":"Error response from daemon: Conflict. The container name \"/Monitoring\" is already in use by container \"8a1244451cc42667a9caca8609ac2026a4124b34e6ce89cb508ef5c73fe2d354\". You have to remove (or rename) that container to be able to reuse that name. If the error persists, try restarting Docker Desktop.","ContainerToolsException.ErrorCode":"DT1001","ContainerToolsException.StackTrace":"   at Microsoft.Docker.DockerWorkspace.PrepareForLaunchAsync(DockerDevelopmentMode dockerDevelopmentMode, Boolean noBuild, IDockerLogger logger, String dockerComposeUpArguments, CancellationToken cancellationToken)\n   at Microsoft.Docker.BuildTasks.PrepareForLaunch.ExecuteCoreAsync(DockerBuildTaskContext context)\n   at Microsoft.Docker.BuildTasks.DockerBuildTask.ExecuteAsync(DockerBuildTaskContext context)","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: Error response from daemon: Conflict. The container name \"/Monitoring\" is already in use by container \"8a1244451cc42667a9caca8609ac2026a4124b34e6ce89cb508ef5c73fe2d354\". You have to remove (or rename) that container to be able to reuse that name.\n   at Microsoft.Docker.DockerWorkspace.PrepareForLaunchAsync(DockerDevelopmentMode dockerDevelopmentMode, Boolean noBuild, IDockerLogger logger, String dockerComposeUpArguments, CancellationToken cancellationToken)\nError code: DT1001\nSeverity: Error\nCommand line: docker-compose  -f \"/Users/adrianbooth67/Projects/Viridia/Dummy2/MonitoringPlatform/docker-compose.yml\" -f \"/Users/adrianbooth67/Projects/Viridia/Dummy2/MonitoringPlatform/docker-compose.override.yml\" -f \"/Users/adrianbooth67/Projects/Viridia/Dummy2/MonitoringPlatform/obj/Docker/docker-compose.vs.debug.g.yml\" -p dockercompose5637921292042572747 --ansi never up -d --build --remove-orphans\nCommand exit code: 1\nCommand output: #1 [internal] load build definition from Dockerfile\n#1 transferring dockerfile: 32B done\n#1 DONE 0.0s\n#2 [internal] load .dockerignore\n#2 transferring context: 35B done\n#2 DONE 0.0s\n#3 [internal] load metadata for mcr.microsoft.com/dotnet/aspnet:7.0\n#3 DONE 0.0s\n#4 [base 1/2] FROM mcr.microsoft.com/dotnet/aspnet:7.0@sha256:db181c925678b0c193c6bdeaf9d04759051aa0a4ab12f91c267f32acc765f35f\n#4 DONE 0.0s\n#5 [base 2/2] WORKDIR /app\n#5 CACHED\n#6 exporting to image\n#6 exporting layers done\n#6 writing image sha256:637e7df6aaeaef4a92c8cd4675f12160fad358e9d3c6cf880ccc6636f6f0cfbc done\n#6 naming to docker.io/library/monitoring:dev done\n#6 DONE 0.0s\nCommand error: Network dockercompose5637921292042572747_default  Creating\nNetwork dockercompose5637921292042572747_default  Created\nContainer Monitoring  Creating\nError response from daemon: Conflict. The container name \"/Monitoring\" is already in use by container \"8a1244451cc42667a9caca8609ac2026a4124b34e6ce89cb508ef5c73fe2d354\". You have to remove (or rename) that container to be able to reuse that name.\n"}]